### ISSUE TITLE
Docker Image missing [Apple ARM]

### ISSUE THREAD

**Issue by slavino** [slovensko-digital/slovensko-sk-api#105]
3.7.2: Pulling from slovensko-digital/slovensko-sk-api
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by jsuchal** [comment]
@slavino za normalnych okolnosti by si toto asi nemal pustat na macu. Jedine kde si to viem predstavit je ze lokalne chces skusat nieco co ma toto ako zavislost.

**Comment by slavino** [comment]
Ano skusat som chcel, nevadi - to vyriesim i bez dockera.
