### ISSUE TITLE
Dynamické presmerovanie URL po prihlásení s tokenom

### ISSUE THREAD

**Issue by MarekBodingerBA** [slovensko-digital/slovensko-sk-api#98]
Ahojte,

momentálne `GET /login` presmeruje na predvolenú URL v premenných prostredia (LOGIN_CALLBACK_URL), bolo by možné v params requestu poslať URL na ktorú má presmerovať? Potrebovali by sme login spárovať s konkrétnymi formulármi (k requestu potrebujeme metadata) a týmto spôsobom dnes nevieme.

Ďakujem.

**Comment by luciajanikova** [comment]
Ahoj, takúto možnosť pridávať nechceme zo security dôvodov. Umožnilo by to prakticky redirect kamkoľvek. Vedeli by sme to teoreticky obmedziť whitelistom, ale nakoľko to je vec, ktorá sa dá vyriešiť na strane aplikácie cez session (odložte si tam callback url a po prihlásení spravíte redirect sami), tak v tom nevidíme veľmi pridanú hodnotu.

**Comment by luciajanikova** [comment]
Ahoj, takúto možnosť pridávať nechceme zo security dôvodov. Umožnilo by to prakticky redirect kamkoľvek. Vedeli by sme to teoreticky obmedziť whitelistom, ale nakoľko to je vec, ktorá sa dá vyriešiť na strane aplikácie cez session (odložte si tam callback url a po prihlásení spravíte redirect sami), tak v tom nevidíme veľmi pridanú hodnotu.

**Comment by jsuchal** [comment]
@MarekBodingerBA este by som dodal, ze takemuto "redirectu hocikam" sa brani aj NASES, cize su na to aj dobre dovody mimo nas.
